#ifndef THEME_H
#define THEME_H

#include <QString>

const QString lightTheme = QStringLiteral( "QMainWindow {"
                                           "	background-color:#f4f2f1;"
                                           "    border-style: none;"
                                           "}"
                                           "QDialog {"
                                           "	background-color:#f4f2f1;"
                                           "}"
                                           "QColorDialog {"
                                           "	background-color:#f4f2f1;"
                                           "}"
                                           "QTextEdit {"
                                           "	background-color:#f4f2f1;"
                                           "	color: black;"
                                           "	selection-background-color: #3379B7;"
                                           "	padding-left:15; padding-top:10; padding-bottom:10; padding-right:10;"
                                           "}"
                                           "MkEdit{"
                                           "	qproperty-blockColor: #e8e4e1;"
                                           "}"
                                           "}"
                                           "QTreeView {"
                                           "    background-color: #f4f2f1;"
                                           "    border-width: 1px; border-style: outset; border-color: gray transparent transparent transparent;"
                                           "    color: black; /* set the text color to white */"
                                           "    image: none;"
                                           "}"
                                           "QLabel {"
                                           "	background: #f4f2f1;"
                                           "    border-width: 1px; border-style: outset; border-color: gray transparent transparent transparent;"
                                           "	color: black;"
                                           "	padding-left:10; padding-right:10; padding-top:10; "
                                           "}"
                                           "QSplitter::handle {"
                                           "    background-color: #adacac;"
                                           "}"
                                           ""
                                           "QSplitter::handle:horizontal {"
                                           "    width: 2px;"
                                           "}"
                                           ""
                                           "QSplitter::handle:vertical {"
                                           "    height: 2px;"
                                           "}"
                                           ""
                                           "QScrollBar:vertical {"
                                           "    background: transparent;"
                                           "    width: 8px; /* Set the width of the scrollbar */"
                                           "    margin: 0px 0px 0px 0px; /* Set the margin */"
                                           "}"
                                           ""
                                           "QScrollBar::handle:vertical {"
                                           "    background: #adacac;"
                                           "    border-radius: 2px; /* Set the border radius of the handle */"
                                           "}"
                                           ""
                                           "QScrollBar::add-line:vertical,"
                                           "QScrollBar::sub-line:vertical {"
                                           "    height: 0px;"
                                           "}"
                                           ""
                                           "QScrollBar::add-page:vertical,"
                                           "QScrollBar::sub-page:vertical {"
                                           "    background: none;"
                                           "}"
                                           ""
                                           "QScrollBar:horizontal {"
                                           "	background: transparent;"
                                           "    border: none;"
                                           "    height: 8px;"
                                           "}"
                                           ""
                                           "QScrollBar::handle:horizontal {"
                                           "    background: #adacac;"
                                           "    border-radius: 4px;"
                                           "}"
                                           ""
                                           "QScrollBar::add-line:horizontal,"
                                           "QScrollBar::sub-line:horizontal {"
                                           "    height: 0px;"
                                           "}"
                                           ""
                                           "QScrollBar::add-page:horizontal,"
                                           "QScrollBar::sub-page:horizontal {"
                                           "    background: none;"
                                           "}"
                                           "QWidget{"
                                           "    border-style: none;"
                                           "}");

const QString darkTheme = QStringLiteral( "QMainWindow {"
                                          "	background-color:#353535;"
                                          "	border-color: transparent"
                                          "}"
                                          "QDialog {"
                                          "	background-color:#353535;"
                                          "}"
                                          "QColorDialog {"
                                          "	background-color:#353535;"
                                          "}"
                                          "QTextEdit {"
                                          "	background-color:#353535;"
                                          "	border-style: none;"
                                          "	color: white;"
                                          "	selection-background-color: #3379B7;"
                                          "	padding-left:15; padding-top:10; padding-bottom:10; padding-right:10"
                                          "}"
                                          "MkEdit{"
                                          "    qproperty-blockColor: #1E1E1E;"
                                          "}"
                                          "QLabel {"
                                          "	background:#353535;"
                                          "	color: white;"
                                          "	padding-left:10; padding-right:10; padding-top:10; "
                                          "}"
                                          "QTreeView {"
                                          "    background-color: #353535;"
                                          "    border-style: none;"
                                          "    color: white; /* set the text color to white */"
                                          "    image: none;"
                                          "}"
                                          "QTreeView::item:selected {"
                                          "    background-color:#707070;"
                                          "    color: white;"
                                          "    image: none;"
                                          "}"
                                          "QSplitter::handle {"
                                          "    background-color: #707070;"
                                          "}"
                                          ""
                                          "QSplitter::handle:horizontal {"
                                          "    width: 2px;"
                                          "}"
                                          ""
                                          "QSplitter::handle:vertical {"
                                          "    height: 2px;"
                                          "}"
                                          ""
                                          "QScrollBar:vertical {"
                                          "    background: transparent;"
                                          "    width: 8px; /* Set the width of the scrollbar */"
                                          "    margin: 0px 0px 0px 0px; /* Set the margin */"
                                          "}"
                                          ""
                                          "QScrollBar::handle:vertical {"
                                          "    background: gray;"
                                          "    border-radius: 2px; /* Set the border radius of the handle */"
                                          "}"
                                          ""
                                          "QScrollBar::add-line:vertical,"
                                          "QScrollBar::sub-line:vertical {"
                                          "    height: 0px;"
                                          "}"
                                          ""
                                          "QScrollBar::add-page:vertical,"
                                          "QScrollBar::sub-page:vertical {"
                                          "    background: none;"
                                          "}"
                                          ""
                                          "QScrollBar:horizontal {"
                                          "	background: transparent;"
                                          "    border: none;"
                                          "    height: 8px;"
                                          "}"
                                          ""
                                          "QScrollBar::handle:horizontal {"
                                          "    background: gray;"
                                          "    border-radius: 4px;"
                                          "}"
                                          ""
                                          "QScrollBar::add-line:horizontal,"
                                          "QScrollBar::sub-line:horizontal {"
                                          "    height: 0px;"
                                          "}"
                                          ""
                                          "QScrollBar::add-page:horizontal,"
                                          "QScrollBar::sub-page:horizontal {"
                                          "    background: none;"
                                          "}"
                                          "QWidget{"
                                          "    border-style: none;"
                                          "}");

#endif // THEME_H
