name: Qt C++

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows

    steps:
    - name: Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64msvc201964'
        dir: '${{ github.workspace }}/Remini/' 
        install-deps: 'true'
        modules: 'widgets'
        cache: 'false'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'false'
        tools: 'toolsifw toolsqtcreator,qt.tools.qtcreator'
        set-env: 'true'
        tools-only: 'false'
