name: Qt C++

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v1
      
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        aqtversion: '==3.1.*'
        version: '6.5.0'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'
        dir: '${{ github.workspace }}\Remini\' 
        cache: 'true'
        cache-key-prefix: 'install-qt-action'
        setup-python: 'false'
        tools: 'tools_cmake'
        
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=Release -B. -DQt6_DIR=${{ github.workspace }}\Remini\Qt\6.5.0\{arch}

    - name: Build the Qt project with CMake
      run: cmake --build build --config Release

    - name: Run test
      run: |
        cd CatchTests
        ${{ github.workspace }}\Remini\Qt\6.5.0\msvc2019_64\bin\windeployqt.exe ReminiTests.exe
        ReminiTests.exe

        
